#!/bin/tcsh
set v=0
echo "*************************************************"
echo "Starting expt script by Michael O'Neill      "
date
echo "*************************************************"
echo "                                                 "
while ( $v != $1 ) 
	echo "Population $v ..."
	python3 ponyge.py --experiment_name "moving_point_nogrid" --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_grid" --replacement "operators.replacement.grid_generational"
	python3 ponyge.py --experiment_name "moving_point_spiral_nogrid" --problem moving_point_spiral --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_spiral_grid" --problem moving_point_spiral --replacement "operators.replacement.grid_generational"
	python3 ponyge.py --experiment_name "moving_point_vision_nogrid" --vision_enabled True --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_vision_grid" --vision_enabled True --replacement "operators.replacement.grid_generational"
	python3 ponyge.py --experiment_name "moving_point_vision_nogrid" --vision_enabled True --field_of_vision 0.5 --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_vision_grid" --vision_enabled True --field_of_vision 0.5 --replacement "operators.replacement.grid_generational"

	python3 ponyge.py --experiment_name "moving_point_nogrid_noxover" --crossover_prob 0.0 --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_grid_noxover" --crossover_prob 0.0 --replacement "operators.replacement.grid_generational"
	python3 ponyge.py --experiment_name "moving_point_spiral_nogrid_noxover" --crossover_prob 0.0 --problem moving_point_spiral --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_spiral_grid_noxover" --crossover_prob 0.0 --problem moving_point_spiral --replacement "operators.replacement.grid_generational"
	python3 ponyge.py --experiment_name "moving_point_vision_nogrid_noxover" --crossover_prob 0.0 --vision_enabled True --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_vision_grid_noxover" --crossover_prob 0.0 --vision_enabled True --replacement "operators.replacement.grid_generational"
	python3 ponyge.py --experiment_name "moving_point_vision_nogrid_noxover" --crossover_prob 0.0 --vision_enabled True --field_of_vision 0.5 --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_vision_grid_noxover" --crossover_prob 0.0 --vision_enabled True --field_of_vision 0.5 --replacement "operators.replacement.grid_generational"

    @ v++
end
#~mike/work/Statify/./statify 0.00000000001 min ge_ $5/$2/$3/XP$2$3-FIT-gen_obj_best_avg_worst.*
#mv ge__* $5/$2/$3/
#~mike/work/Statify/./statify_size $5/$2/$3/XP$2$3-SIZE-gen_max_avg_min_effmax_effavg_effmin.dat.*
#mv statify_size.dat $5/$2/$3/
echo "*************************************************"
echo "expt script finished @                       "
date
echo "*************************************************"

