#!/bin/tcsh
set v=0
echo "*************************************************"
echo "Starting expt script by Michael O'Neill      "
date
echo "*************************************************"
echo "                                                 "
while ( $v != $1 ) 
	echo "Population $v ..."
	python3 ponyge.py --experiment_name "moving_point_nogrid" --generations 100 --problem moving_point --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_grid" --generations 100 --problem moving_point --replacement "operators.replacement.grid_generational"
	python3 ponyge.py --experiment_name "moving_point_spiral_nogrid" --problem moving_point_spiral --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_spiral_grid" --problem moving_point_spiral --replacement "operators.replacement.grid_generational"
	python3 ponyge.py --experiment_name "moving_point_vision_01_nogrid" --problem moving_point_step --mp_target_file "/datasets/random.csv" --vision_enabled True --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_vision_01_grid" --problem moving_point_step --mp_target_file "/datasets/random.csv" --vision_enabled True --replacement "operators.replacement.grid_generational"
	python3 ponyge.py --experiment_name "moving_point_vision_05_nogrid" --problem moving_point_step --mp_target_file "/datasets/random.csv" --vision_enabled True --field_of_vision 0.5 --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_vision_05_grid" --problem moving_point_step --mp_target_file "/datasets/random.csv" --vision_enabled True --field_of_vision 0.5 --replacement "operators.replacement.grid_generational"
	python3 ponyge.py --experiment_name "moving_point_vision_09_nogrid" --problem moving_point_step --mp_target_file "/datasets/random.csv" --vision_enabled True --field_of_vision 0.9 --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_vision_09_grid" --problem moving_point_step --mp_target_file "/datasets/random.csv" --vision_enabled True --field_of_vision 0.9 --replacement "operators.replacement.grid_generational"

	python3 ponyge.py --experiment_name "moving_point_nogrid_noxover" --generations 100 --problem moving_point --crossover_prob 0.0 --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_grid_noxover" --generations 100 --problem moving_point --crossover_prob 0.0 --replacement "operators.replacement.grid_generational"
	python3 ponyge.py --experiment_name "moving_point_spiral_nogrid_noxover" --crossover_prob 0.0 --problem moving_point_spiral --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_spiral_grid_noxover" --crossover_prob 0.0 --problem moving_point_spiral --replacement "operators.replacement.grid_generational"
	python3 ponyge.py --experiment_name "moving_point_vision_01_nogrid_noxover" --problem moving_point_step --mp_target_file "/datasets/random.csv" --crossover_prob 0.0 --vision_enabled True --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_vision_01_grid_noxover" --problem moving_point_step --mp_target_file "/datasets/random.csv" --crossover_prob 0.0 --vision_enabled True --replacement "operators.replacement.grid_generational"
	python3 ponyge.py --experiment_name "moving_point_vision_05_nogrid_noxover" --problem moving_point_step --mp_target_file "/datasets/random.csv" --crossover_prob 0.0 --vision_enabled True --field_of_vision 0.5 --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_vision_05_grid_noxover" --problem moving_point_step --mp_target_file "/datasets/random.csv" --crossover_prob 0.0 --vision_enabled True --field_of_vision 0.5 --replacement "operators.replacement.grid_generational"
	python3 ponyge.py --experiment_name "moving_point_vision_09_nogrid_noxover" --problem moving_point_step --mp_target_file "/datasets/random.csv" --crossover_prob 0.0 --vision_enabled True --field_of_vision 0.9 --replacement "operators.replacement.generational"
	python3 ponyge.py --experiment_name "moving_point_vision_09_grid_noxover" --problem moving_point_step --mp_target_file "/datasets/random.csv" --crossover_prob 0.0 --vision_enabled True --field_of_vision 0.9 --replacement "operators.replacement.grid_generational"

    @ v++
end
./statsscript
echo "*************************************************"
echo "expt script finished @                       "
date
echo "*************************************************"

